apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddns_update.fullname" . }}-secret
  labels:
    {{- include "ddns_update.labels" . | nindent 4 }}
type: Opaque
data:
  aws-access-key-id: {{ .Values.secret.aws_access_key_id | b64enc | quote }}
  aws-secret-access-key: {{ .Values.secret.aws_secret_access_key | b64enc | quote }}
