apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ddns_update.fullname" . }}-config
  labels:
    {{- include "ddns_update.labels" . | nindent 4 }}
data:
  dns-zone: {{ .Values.config.dns_zone }}
  timezone: {{ .Values.config.timezone }}

